# Generated by Django 2.2.6 on 2019-10-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_proveedor', models.CharField(choices=[('BN', 'Boca Nación'), ('PP', 'Proveedor Privado'), ('EM', 'Estado Municipal'), ('EP', 'Estado Provincial')], default='', max_length=2)),
                ('entidad', models.CharField(default='', max_length=50)),
                ('ubicacion', models.CharField(default='', max_length=80)),
                ('localidad', models.CharField(default='', max_length=40)),
                ('provincia', models.CharField(default='', max_length=40)),
                ('nombre_contacto', models.CharField(default='', max_length=40)),
                ('observacion', models.TextField(default='')),
            ],
            options={
                'verbose_name_plural': 'Proveedor',
                'verbose_name': 'Proveedor',
            },
        ),
    ]
