# Generated by Django 2.2.6 on 2019-10-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
