# Generated by Django 2.2.6 on 2019-10-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0002_auto_20191010_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='entidad',
            new_name='nombre_compania_o_entidad',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_de_proveedor',
            field=models.CharField(choices=[('BN', 'Boca Nación'), ('CM', 'Convenio Merienda')], default='', max_length=2),
        ),
    ]
