# Generated by Django 2.2.6 on 2019-10-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0004_auto_20191010_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_de_proveedor',
            field=models.CharField(choices=[('Boca Nación', 'Boca Nación'), ('Convenio Merienda', 'Convenio Merienda')], default='', max_length=20),
        ),
    ]
