# Generated by Django 2.1.7 on 2019-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedores', '0005_auto_20191010_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
