# Generated by Django 2.2.6 on 2019-10-11 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0005_auto_20191010_1503'),
        ('Organizacion', '0004_auto_20191010_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresosAPuntosDeRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], max_length=9)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Ingresos a Punto de Recepción',
                'verbose_name': 'Ingresos a Punto de Recepción',
            },
        ),
        migrations.CreateModel(
            name='EgresosPuntoDeRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], max_length=9)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.Proveedor')),
            ],
            options={
                'verbose_name_plural': 'Egreso a Punto de Recepción',
                'verbose_name': 'Egreso Punto de Recepción',
            },
        ),
    ]
