# Generated by Django 2.2.6 on 2019-11-20 19:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Distribucion',
                'verbose_name_plural': 'Distribuciones',
            },
        ),
        migrations.CreateModel(
            name='DistribucionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_asignado', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Distribucion Producto',
                'verbose_name_plural': 'Distribuciones Productos',
            },
        ),
        migrations.CreateModel(
            name='EgresosPuntoDeRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], default='Borrador', max_length=9)),
                ('fecha_y_hora_de_egreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_y_hora_de_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Egreso Punto de Recepción',
                'verbose_name_plural': 'Egreso Punto de Recepción',
                'ordering': ['-fecha_y_hora_de_registro'],
            },
        ),
        migrations.CreateModel(
            name='IngresosAPuntosDeRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_y_hora_de_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], default='Borrador', max_length=9)),
                ('fecha_y_hora_de_registro', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Ingresos a Punto de Recepción',
                'verbose_name_plural': 'Ingresos a Punto de Recepción',
                'ordering': ['-fecha_y_hora_de_registro'],
            },
        ),
        migrations.CreateModel(
            name='LineaDeEgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Línea de Egreso de PR',
                'verbose_name_plural': 'Líneas de Egreso de PR',
            },
        ),
        migrations.CreateModel(
            name='LineaDistribucionProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.FloatField(default=0)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.DistribucionProducto')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo', verbose_name='Punto de Consumo')),
            ],
            options={
                'verbose_name': 'Linea de Distribucion de Producto',
                'verbose_name_plural': 'Lineas de Distribucion de Productos',
            },
        ),
        migrations.CreateModel(
            name='LineaDeIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion')),
            ],
            options={
                'verbose_name': 'Línea de Ingreso a PR',
                'verbose_name_plural': 'Líneas de Ingreso a PR',
            },
        ),
    ]
