# Generated by Django 2.2.6 on 2019-11-16 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Proveedores', '0005_auto_20191010_1503'),
        ('Organizacion', '0001_initial'),
        ('Movimientos', '0001_initial'),
        ('Productos', '0009_auto_20191015_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineadistribucionproducto',
            name='pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo', verbose_name='Punto de Consumo'),
        ),
        migrations.AddField(
            model_name='lineadeing',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion'),
        ),
        migrations.AddField(
            model_name='lineadeing',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='lineadeegr',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.EgresosPuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='lineadeegr',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proveedores.Proveedor'),
        ),
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo'),
        ),
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='distribucionproducto',
            name='distribucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.Distribucion', verbose_name='Distribucion'),
        ),
        migrations.AddField(
            model_name='distribucionproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='ingreso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion', verbose_name='Ingreso'),
        ),
    ]
