# Generated by Django 2.1.7 on 2019-11-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0001_initial'),
        ('Productos', '0001_initial'),
        ('Proveedores', '0005_auto_20191010_1503'),
        ('Movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaListaDestinosEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Linea de Destino',
                'verbose_name_plural': 'Lineas de Destino',
            },
        ),
        migrations.CreateModel(
            name='ListaDestinosEgreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=20)),
                ('puntoDeRecepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion')),
            ],
            options={
                'verbose_name': 'Lista de Destinos',
                'verbose_name_plural': 'Listas de Destinos',
            },
        ),
        migrations.AddField(
            model_name='distribucion',
            name='ingreso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion', verbose_name='Ingreso'),
        ),
        migrations.AddField(
            model_name='distribucionproducto',
            name='distribucion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.Distribucion', verbose_name='Distribucion'),
        ),
        migrations.AddField(
            model_name='distribucionproducto',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.VarianteProducto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='destino',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo'),
        ),
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='origen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='destino',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='origen',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Proveedores.Proveedor'),
        ),
        migrations.AddField(
            model_name='lineadeegr',
            name='movimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.EgresosPuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='lineadeegr',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.VarianteProducto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='lineadeing',
            name='producto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.VarianteProducto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='lineadeing',
            name='movimiento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion'),
        ),
        migrations.AddField(
            model_name='linealistadestinosegreso',
            name='listaDeDestinos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.ListaDestinosEgreso'),
        ),
        migrations.AddField(
            model_name='linealistadestinosegreso',
            name='puntoDeConsumo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='listaDeDestinos',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movimientos.ListaDestinosEgreso'),
        ),
    ]
