# Generated by Django 2.2.6 on 2019-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresospuntoderecepcion',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], default='Borrador', max_length=9),
        ),
        migrations.AlterField(
            model_name='ingresosapuntosderecepcion',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Validado', 'Validado')], default='Borrador', max_length=9),
        ),
    ]
