# Generated by Django 2.2.6 on 2019-10-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20191010_1444'),
        ('Movimientos', '0002_auto_20191011_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='linea_de_pedido',
            field=models.ManyToManyField(to='Productos.Producto'),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='linea_de_pedido',
            field=models.ManyToManyField(to='Productos.Producto'),
        ),
    ]
