# Generated by Django 2.2.6 on 2019-10-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20191010_1444'),
        ('Movimientos', '0003_auto_20191013_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresospuntoderecepcion',
            name='linea_de_pedido',
        ),
        migrations.RemoveField(
            model_name='ingresosapuntosderecepcion',
            name='linea_de_pedido',
        ),
        migrations.CreateModel(
            name='LineaDePedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto', verbose_name='Producto')),
            ],
        ),
    ]
