# Generated by Django 2.1.7 on 2019-11-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0004_auto_20191125_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionproducto',
            name='producto',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='Productos.VarianteProducto', verbose_name='Producto'),
        ),
    ]
