# Generated by Django 2.2.6 on 2019-10-13 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0004_auto_20191013_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineadepedido',
            options={'verbose_name': 'Línea de Pedido', 'verbose_name_plural': 'Línea de Pedido'},
        ),
    ]
