# Generated by Django 2.2.6 on 2019-10-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0005_auto_20191013_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineadepedido',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='lineadepedido',
            name='scantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
