# Generated by Django 2.2.6 on 2019-10-14 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0007_auto_20191014_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresospuntoderecepcion',
            old_name='fecha_registro',
            new_name='fecha_y_hora_de_registro',
        ),
        migrations.RenameField(
            model_name='ingresosapuntosderecepcion',
            old_name='fecha_registro',
            new_name='fecha_y_hora_de_registro',
        ),
    ]
