# Generated by Django 2.1.7 on 2019-11-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0008_auto_20191125_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linealistadestinosegreso',
            name='listaDeDestinos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.ListaDestinosEgreso'),
        ),
        migrations.AlterField(
            model_name='linealistadestinosegreso',
            name='puntoDeConsumo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeConsumo'),
        ),
    ]
