# Generated by Django 2.2.6 on 2019-10-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0008_auto_20191014_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='lineas_de_producto',
            field=models.ManyToManyField(to='Movimientos.LineaDePedido'),
        ),
    ]
