# Generated by Django 2.2.6 on 2019-10-14 22:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0009_egresospuntoderecepcion_lineas_de_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresospuntoderecepcion',
            name='fecha_y_hora_de_egreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ingresosapuntosderecepcion',
            name='fecha_y_hora_de_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='egresospuntoderecepcion',
            name='fecha_y_hora_de_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ingresosapuntosderecepcion',
            name='fecha_y_hora_de_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
