# Generated by Django 2.2.6 on 2019-10-14 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_auto_20191013_1745'),
        ('Movimientos', '0010_auto_20191014_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaDePedidoEgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Línea de Pedido',
            },
        ),
        migrations.CreateModel(
            name='LineaDePedidoIng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.IngresosAPuntosDeRecepcion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Línea de Pedido',
            },
        ),
        migrations.RemoveField(
            model_name='egresospuntoderecepcion',
            name='lineas_de_producto',
        ),
        migrations.DeleteModel(
            name='LineaDePedido',
        ),
        migrations.AddField(
            model_name='lineadepedidoegr',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movimientos.EgresosPuntoDeRecepcion'),
        ),
        migrations.AddField(
            model_name='lineadepedidoegr',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto', verbose_name='Producto'),
        ),
    ]
