# Generated by Django 2.2.6 on 2019-10-15 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0011_auto_20191014_2050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresospuntoderecepcion',
            options={'ordering': ['-fecha_y_hora_de_registro'], 'verbose_name': 'Egreso Punto de Recepción', 'verbose_name_plural': 'Egreso a Punto de Recepción'},
        ),
        migrations.AlterModelOptions(
            name='ingresosapuntosderecepcion',
            options={'ordering': ['-fecha_y_hora_de_registro'], 'verbose_name': 'Ingresos a Punto de Recepción', 'verbose_name_plural': 'Ingresos a Punto de Recepción'},
        ),
        migrations.AlterModelOptions(
            name='lineadepedidoegr',
            options={'verbose_name': 'Línea de Pedido Egreso de PR', 'verbose_name_plural': 'Línea de Pedido Egreso de PR'},
        ),
        migrations.AlterModelOptions(
            name='lineadepedidoing',
            options={'verbose_name': 'Línea de Pedido Ingreso a PR', 'verbose_name_plural': 'Línea de Pedido Ingreso a PR'},
        ),
    ]
