# Generated by Django 2.2.6 on 2019-10-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_auto_20191013_1745'),
        ('Movimientos', '0012_auto_20191015_1056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineaDePedidoEgr',
            new_name='LineaDeEgr',
        ),
        migrations.RenameModel(
            old_name='LineaDePedidoIng',
            new_name='LineaDeIng',
        ),
        migrations.AlterModelOptions(
            name='lineadeegr',
            options={'verbose_name': 'Línea de Egreso de PR', 'verbose_name_plural': 'Línea de Egreso de PR'},
        ),
        migrations.AlterModelOptions(
            name='lineadeing',
            options={'verbose_name': 'Línea de Ingreso a PR', 'verbose_name_plural': 'Línea de Ingreso a PR'},
        ),
    ]
