# Generated by Django 2.2.6 on 2019-10-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movimientos', '0014_auto_20191015_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresospuntoderecepcion',
            options={'ordering': ['-fecha_y_hora_de_registro'], 'verbose_name': 'Egreso Punto de Recepción', 'verbose_name_plural': 'Egreso Punto de Recepción'},
        ),
    ]
