# Generated by Django 2.2.6 on 2019-10-10 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoDeRecepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('observacion', models.TextField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Recepción',
                'verbose_name_plural': 'Punto de Recepción',
            },
        ),
        migrations.CreateModel(
            name='PuntoDeConsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=80)),
                ('localidad', models.CharField(max_length=40)),
                ('provincia', models.CharField(max_length=40)),
                ('tipo_de_establecimiento', models.CharField(choices=[('CC', 'Casa Comunitaria'), ('CB', 'Centro Barrial'), ('CR', 'Comedor'), ('CO', 'Cooperativa'), ('ME', 'Merendero'), ('MC', 'Merendero-Comedor')], default='', max_length=2)),
                ('observacion', models.TextField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Consumo',
                'verbose_name_plural': 'Punto de Consumo',
            },
        ),
    ]
