# Generated by Django 2.2.6 on 2019-10-10 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Organizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntodeconsumo',
            name='responsable',
        ),
        migrations.AddField(
            model_name='puntodeconsumo',
            name='punto_de_recepcion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.PuntoDeRecepcion'),
        ),
        migrations.CreateModel(
            name='Regional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=80)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Regional',
                'verbose_name': 'Regional',
            },
        ),
        migrations.AddField(
            model_name='puntodeconsumo',
            name='regional',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organizacion.Regional'),
        ),
    ]
