# Generated by Django 2.1.7 on 2019-11-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntodeconsumo',
            name='responsable',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='puntodeconsumo',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='puntoderecepcion',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='puntoderecepcion',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
