# Generated by Django 2.2.6 on 2019-10-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0002_auto_20191010_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeconsumo',
            name='observacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='puntodeconsumo',
            name='tipo_de_establecimiento',
            field=models.CharField(choices=[('Casa Comunitaria', 'Casa Comunitaria'), ('Centro Barrial', 'Centro Barrial'), ('Comendor', 'Comedor'), ('Cooperativa', 'Cooperativa'), ('Merendero', 'Merendero'), ('Merendero-Comedor', 'Merendero-Comedor')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='puntoderecepcion',
            name='observacion',
            field=models.TextField(blank=True),
        ),
    ]
