# Generated by Django 2.2.6 on 2019-10-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0003_auto_20191010_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntodeconsumo',
            name='regional',
        ),
        migrations.AddField(
            model_name='puntoderecepcion',
            name='tipo_de_establecimiento',
            field=models.CharField(choices=[('Casa Comunitaria', 'Casa Comunitaria'), ('Centro Barrial', 'Centro Barrial'), ('Comendor', 'Comedor'), ('Cooperativa', 'Cooperativa'), ('Merendero', 'Merendero'), ('Merendero-Comedor', 'Merendero-Comedor')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Regional',
        ),
    ]
