# Generated by Django 2.2.6 on 2019-10-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0004_auto_20191010_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoderecepcion',
            name='tipo_de_establecimiento',
            field=models.CharField(choices=[('Casa Compañero', 'Casa Compañero'), ('Centro Barrial', 'Centro Barrial'), ('Comendor', 'Comedor'), ('Cooperativa', 'Cooperativa'), ('Merendero-Comedor', 'Merendero-Comedor')], default='', max_length=20),
        ),
    ]
