# Generated by Django 2.2.6 on 2019-10-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizacion', '0005_auto_20191011_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntodeconsumo',
            name='tipo_de_establecimiento',
            field=models.CharField(choices=[('Casa Comunitaria', 'Casa Comunitaria'), ('Centro Barrial', 'Centro Barrial'), ('Comendor', 'Comedor'), ('Cooperativa', 'Cooperativa'), ('Merendero', 'Merendero'), ('Merendero-Comedor', 'Merendero-Comedor')], default='', max_length=20),
        ),
    ]
