# Generated by Django 2.2.6 on 2019-10-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_alimento', models.CharField(choices=[('AF', 'Alimento Fresco'), ('AS', 'Alimento Seco')], default='', max_length=2)),
                ('nombre', models.CharField(max_length=30)),
                ('observacion', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Alimento',
                'verbose_name_plural': 'Alimento',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Alimento')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Bulto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.Producto')),
            ],
        ),
    ]
