# Generated by Django 2.2.6 on 2019-10-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20191010_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='responsable',
            new_name='alimento',
        ),
    ]
