# Generated by Django 2.2.6 on 2019-10-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_auto_20191010_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulto',
            options={'verbose_name': 'Bulto', 'verbose_name_plural': 'Bulto'},
        ),
        migrations.RenameField(
            model_name='bulto',
            old_name='cantidad',
            new_name='cantidad_de_paquetes',
        ),
    ]
