# Generated by Django 2.2.6 on 2019-10-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_auto_20191010_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('LT', 'Litros'), ('GR', 'Gramos'), ('UN', 'Unidad')], default='', max_length=2),
        ),
        migrations.DeleteModel(
            name='Bulto',
        ),
    ]
