# Generated by Django 2.2.6 on 2019-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0005_auto_20191010_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_del_producto',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.FloatField(default=0, verbose_name='Cantidad'),
        ),
    ]
