# Generated by Django 2.2.6 on 2019-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_auto_20191013_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('KG', 'Kilogramos'), ('LT', 'Litros'), ('UN', 'Unidad')], default='', max_length=2),
        ),
    ]
