# Generated by Django 2.2.6 on 2019-10-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_auto_20191013_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_del_producto',
            new_name='denominacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='alimento',
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('Alimento Seco', 'Alimento Seco'), ('Alimento Fresco', 'Alimento Fresco'), ('Textil', 'Textil'), ('Obras', 'Obras'), ('Otros', 'Otros')], default='', max_length=15),
        ),
        migrations.DeleteModel(
            name='Alimento',
        ),
    ]
