# Generated by Django 2.2.6 on 2019-10-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_auto_20191015_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='unidad_de_medida',
            field=models.CharField(choices=[('Kilo', 'Kilogramos'), ('Litro', 'Litros'), ('Unidad', 'Unidad')], default='', max_length=15),
        ),
    ]
